### ISSUE TITLE
Cannot extract feature_importance

### ISSUE THREAD

**Issue by Qotov** [harshakokel/KiGB#2]
Is there a way of model feature importance extraction? I cannot do it with the internal method of scikit-learn.
![image](https://user-images.githubusercontent.com/49810237/93108660-5d1d4680-f6b3-11ea-8f43-2c64b0fe5dc3.png)

**Comment by harshakokel** [comment]
Hello @Qotov,

Thank you for highlighting the error, I have fixed the issue. Feature importance can now be extracted as shown below.

```
'''Step 5: Test the model'''
Y_pred = kigb.predict(X_test)
feature_importance = kigb.feature_importance()
```

Thanks,
Harsha Kokel.
